/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface RenameNotebook$Params {
  id: string;
      body: {
'title': string;
}
}

export function renameNotebook(http: HttpClient, rootUrl: string, params: RenameNotebook$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'id': string;
'title': string;
'createdAt': string;
}>> {
  const rb = new RequestBuilder(rootUrl, renameNotebook.PATH, 'patch');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      'id': string;
      'title': string;
      'createdAt': string;
      }>;
    })
  );
}

renameNotebook.PATH = '/notebooks/{id}';
