/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface SearchChatThreads$Params {

/**
 * Keywords, matched literally in questions and answers; blank returns no results.
 */
  q?: string;
  notebookId: string;
}

export function searchChatThreads(http: HttpClient, rootUrl: string, params: SearchChatThreads$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<{
'threadId': string;
'threadTitle': string;
'askedBy': {
'id': string;
'email': string;
};

/**
 * When the question was asked.
 */
'askedAt': string;
'questionId': string;

/**
 * Where a result opens the Chat Thread.
 */
'answerId': string;

/**
 * The question, whole, its matches flagged.
 */
'question': Array<{
'text': string;
'match': boolean;
}>;

/**
 * Up to two excerpts of the answer around its matches, flagged.
 */
'answer': Array<{
'text': string;
'match': boolean;
}>;
}>>> {
  const rb = new RequestBuilder(rootUrl, searchChatThreads.PATH, 'get');
  if (params) {
    rb.query('q', params.q, {});
    rb.path('notebookId', params.notebookId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<{
      'threadId': string;
      'threadTitle': string;
      'askedBy': {
      'id': string;
      'email': string;
      };
      
      /**
       * When the question was asked.
       */
      'askedAt': string;
      'questionId': string;
      
      /**
       * Where a result opens the Chat Thread.
       */
      'answerId': string;
      
      /**
       * The question, whole, its matches flagged.
       */
      'question': Array<{
      'text': string;
      'match': boolean;
      }>;
      
      /**
       * Up to two excerpts of the answer around its matches, flagged.
       */
      'answer': Array<{
      'text': string;
      'match': boolean;
      }>;
      }>>;
    })
  );
}

searchChatThreads.PATH = '/notebooks/{notebookId}/search/threads';
