/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DocumentFailure } from '../../models/document-failure';

export interface SearchNotebook$Params {

/**
 * What to search for — keywords or a topic, matched semantically, not literally.
 */
  q: string;

/**
 * How many Documents to return, best match first.
 */
  limit?: number;
  notebookId: string;
}

export function searchNotebook(http: HttpClient, rootUrl: string, params: SearchNotebook$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<{
'id': string;
'notebookId': string;
'filename': string;
'status': 'queued' | 'converting' | 'converted' | 'summarizing' | 'summarized' | 'indexing' | 'ready' | 'failed';
'failure': DocumentFailure | null;
'abstract': string | null;
'createdAt': string;
'latestVersion': {
'id': string;
'versionNumber': number;
'mimeType': string;
'sizeBytes': number;
'createdAt': string;
};

/**
 * Cosine similarity of this Document's best-matching Chunk to the query, 1 being identical. Results are ordered by it, best first.
 */
'score': number;
}>>> {
  const rb = new RequestBuilder(rootUrl, searchNotebook.PATH, 'get');
  if (params) {
    rb.query('q', params.q, {});
    rb.query('limit', params.limit, {});
    rb.path('notebookId', params.notebookId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<{
      'id': string;
      'notebookId': string;
      'filename': string;
      'status': 'queued' | 'converting' | 'converted' | 'summarizing' | 'summarized' | 'indexing' | 'ready' | 'failed';
      'failure': DocumentFailure | null;
      'abstract': string | null;
      'createdAt': string;
      'latestVersion': {
      'id': string;
      'versionNumber': number;
      'mimeType': string;
      'sizeBytes': number;
      'createdAt': string;
      };
      
      /**
       * Cosine similarity of this Document's best-matching Chunk to the query, 1 being identical. Results are ordered by it, best first.
       */
      'score': number;
      }>>;
    })
  );
}

searchNotebook.PATH = '/notebooks/{notebookId}/search';
