/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface SearchNotebook$Params {

/**
 * Keywords, matched literally in the Chunks of each latest ready Version, accents and case ignored; web-search syntax ("a phrase", -word, or). Blank returns no results.
 */
  q?: string;
  notebookId: string;
}

export function searchNotebook(http: HttpClient, rootUrl: string, params: SearchNotebook$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<{
'documentId': string;
'filename': string;

/**
 * The title Stage 2 extracted from the Version, or null when it stated none.
 */
'title': string | null;

/**
 * The Markdown headings the Chunk sits under, outermost first.
 */
'headingPath': Array<string>;

/**
 * Where the matching Chunk sits — what opening the result shows.
 */
'match': {

/**
 * The Document Version the Chunk belongs to.
 */
'versionId': string;

/**
 * The matching Chunk.
 */
'chunkId': string;

/**
 * Start of the Chunk in the Version's Converted Markdown; null when it could not be located.
 */
'charStart': number | null;

/**
 * End of that range, exclusive.
 */
'charEnd': number | null;
};

/**
 * An Excerpt (GLOSSARY.md): about two lines of the Chunk around its matches, Markdown markers stripped, the matched words flagged.
 */
'excerpt': Array<{
'text': string;
'match': boolean;
}>;
}>>> {
  const rb = new RequestBuilder(rootUrl, searchNotebook.PATH, 'get');
  if (params) {
    rb.query('q', params.q, {});
    rb.path('notebookId', params.notebookId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<{
      'documentId': string;
      'filename': string;
      
      /**
       * The title Stage 2 extracted from the Version, or null when it stated none.
       */
      'title': string | null;
      
      /**
       * The Markdown headings the Chunk sits under, outermost first.
       */
      'headingPath': Array<string>;
      
      /**
       * Where the matching Chunk sits — what opening the result shows.
       */
      'match': {
      
      /**
       * The Document Version the Chunk belongs to.
       */
      'versionId': string;
      
      /**
       * The matching Chunk.
       */
      'chunkId': string;
      
      /**
       * Start of the Chunk in the Version's Converted Markdown; null when it could not be located.
       */
      'charStart': number | null;
      
      /**
       * End of that range, exclusive.
       */
      'charEnd': number | null;
      };
      
      /**
       * An Excerpt (GLOSSARY.md): about two lines of the Chunk around its matches, Markdown markers stripped, the matched words flagged.
       */
      'excerpt': Array<{
      'text': string;
      'match': boolean;
      }>;
      }>>;
    })
  );
}

searchNotebook.PATH = '/notebooks/{notebookId}/search';
