/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface DeleteChatThread$Params {
  notebookId: string;
  threadId: string;
}

export function deleteChatThread(http: HttpClient, rootUrl: string, params: DeleteChatThread$Params, context?: HttpContext): Observable<StrictHttpResponse<'null'>> {
  const rb = new RequestBuilder(rootUrl, deleteChatThread.PATH, 'delete');
  if (params) {
    rb.path('notebookId', params.notebookId, {});
    rb.path('threadId', params.threadId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<'null'>;
    })
  );
}

deleteChatThread.PATH = '/notebooks/{notebookId}/threads/{threadId}';
