/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface ListChatMessages$Params {
  notebookId: string;
  threadId: string;
}

export function listChatMessages(http: HttpClient, rootUrl: string, params: ListChatMessages$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<{
'id': string;
'threadId': string;
'role': 'user' | 'assistant';
'content': string;
'askedBy': {
'id': string;
'email': string;
};
'citations': Array<{
'id': string;
'marker': number;
'documentId': string;
'documentVersionId': string;
'versionNumber': number;
'chunkId': string;
'filename': string;
'headingPath': Array<string>;
'charStart': number | null;
'charEnd': number | null;
}>;
'createdAt': string;
}>>> {
  const rb = new RequestBuilder(rootUrl, listChatMessages.PATH, 'get');
  if (params) {
    rb.path('notebookId', params.notebookId, {});
    rb.path('threadId', params.threadId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<{
      'id': string;
      'threadId': string;
      'role': 'user' | 'assistant';
      'content': string;
      'askedBy': {
      'id': string;
      'email': string;
      };
      'citations': Array<{
      'id': string;
      'marker': number;
      'documentId': string;
      'documentVersionId': string;
      'versionNumber': number;
      'chunkId': string;
      'filename': string;
      'headingPath': Array<string>;
      'charStart': number | null;
      'charEnd': number | null;
      }>;
      'createdAt': string;
      }>>;
    })
  );
}

listChatMessages.PATH = '/notebooks/{notebookId}/threads/{threadId}/messages';
