/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface RenameChatThread$Params {
  notebookId: string;
  threadId: string;
      body: {
'title': string;
}
}

export function renameChatThread(http: HttpClient, rootUrl: string, params: RenameChatThread$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'id': string;
'notebookId': string;
'title': string;
'author': {
'id': string;
'email': string;
};
'createdAt': string;
}>> {
  const rb = new RequestBuilder(rootUrl, renameChatThread.PATH, 'patch');
  if (params) {
    rb.path('notebookId', params.notebookId, {});
    rb.path('threadId', params.threadId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      'id': string;
      'notebookId': string;
      'title': string;
      'author': {
      'id': string;
      'email': string;
      };
      'createdAt': string;
      }>;
    })
  );
}

renameChatThread.PATH = '/notebooks/{notebookId}/threads/{threadId}';
