/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface SendChatMessage$Params {
  notebookId: string;
  threadId: string;
      body: {
'content': string;
}
}

export function sendChatMessage(http: HttpClient, rootUrl: string, params: SendChatMessage$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'question': {
'id': string;
'threadId': string;
'role': 'user' | 'assistant';
'content': string;
'askedBy': {
'id': string;
'email': string;
};
'createdAt': string;
};
'answer': {
'id': string;
'threadId': string;
'role': 'user' | 'assistant';
'content': string;
'askedBy': {
'id': string;
'email': string;
};
'createdAt': string;
};
}>> {
  const rb = new RequestBuilder(rootUrl, sendChatMessage.PATH, 'post');
  if (params) {
    rb.path('notebookId', params.notebookId, {});
    rb.path('threadId', params.threadId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      'question': {
      'id': string;
      'threadId': string;
      'role': 'user' | 'assistant';
      'content': string;
      'askedBy': {
      'id': string;
      'email': string;
      };
      'createdAt': string;
      };
      'answer': {
      'id': string;
      'threadId': string;
      'role': 'user' | 'assistant';
      'content': string;
      'askedBy': {
      'id': string;
      'email': string;
      };
      'createdAt': string;
      };
      }>;
    })
  );
}

sendChatMessage.PATH = '/notebooks/{notebookId}/threads/{threadId}/messages';
