/**
 * The message to show a user for a failed call through the generated
 * ng-openapi-gen client.
 *
 * All five SignalStores need the same thing and had each written the same
 * function, byte for byte. It is one rule, and it is a rule about the shape of
 * *this* client's failures rather than about any one store's domain: the
 * generated client rejects with an Angular `HttpErrorResponse`, whose `error`
 * is the parsed JSON body — and every backend error route answers the same
 * `{ message }` shape (`errorResponseSchema`). So the backend's own wording is
 * what a user should see, because it is the half that knows what went wrong:
 * "A Document named 'x' already exists in this Notebook" is worth far more
 * than "Failed to restore Document."
 *
 * `fallback` is the store's own sentence, used only when there is no body to
 * read — an offline browser, a CORS failure, a 502 from something in front of
 * the backend.
 *
 * Lives under `shared/` rather than in `api/`, which is wholly generated by
 * `pnpm run openapi:generate` and must hold nothing hand-written.
 */
export function errorMessage(err: unknown, fallback: string): string {
  if (err && typeof err === 'object' && 'error' in err) {
    const body = (err as { error?: unknown }).error;
    if (body && typeof body === 'object' && 'message' in body && typeof body.message === 'string') {
      return body.message;
    }
  }
  return err instanceof Error ? err.message : fallback;
}
