/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { getCurrentUser } from '../fn/auth/get-current-user';
import { GetCurrentUser$Params } from '../fn/auth/get-current-user';
import { login } from '../fn/auth/login';
import { Login$Params } from '../fn/auth/login';
import { logout } from '../fn/auth/logout';
import { Logout$Params } from '../fn/auth/logout';
import { register } from '../fn/auth/register';
import { Register$Params } from '../fn/auth/register';

@Injectable({ providedIn: 'root' })
export class AuthService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `register()` */
  static readonly RegisterPath = '/auth/register';

  /**
   * Register a new user account.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `register()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  register$Response(params: Register$Params, context?: HttpContext): Promise<StrictHttpResponse<{
'id': string;
'email': string;
'createdAt': string;
}>> {
    const obs = register(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Register a new user account.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `register$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  register(params: Register$Params, context?: HttpContext): Promise<{
'id': string;
'email': string;
'createdAt': string;
}> {
    const resp = this.register$Response(params, context);
    return resp.then((r: StrictHttpResponse<{
'id': string;
'email': string;
'createdAt': string;
}>): {
'id': string;
'email': string;
'createdAt': string;
} => r.body);
  }

  /** Path part for operation `login()` */
  static readonly LoginPath = '/auth/login';

  /**
   * Log in and receive a session cookie.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `login()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  login$Response(params: Login$Params, context?: HttpContext): Promise<StrictHttpResponse<{
'id': string;
'email': string;
'createdAt': string;
}>> {
    const obs = login(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Log in and receive a session cookie.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `login$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  login(params: Login$Params, context?: HttpContext): Promise<{
'id': string;
'email': string;
'createdAt': string;
}> {
    const resp = this.login$Response(params, context);
    return resp.then((r: StrictHttpResponse<{
'id': string;
'email': string;
'createdAt': string;
}>): {
'id': string;
'email': string;
'createdAt': string;
} => r.body);
  }

  /** Path part for operation `logout()` */
  static readonly LogoutPath = '/auth/logout';

  /**
   * Log out and clear the session cookie.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `logout()` instead.
   *
   * This method doesn't expect any request body.
   */
  logout$Response(params?: Logout$Params, context?: HttpContext): Promise<StrictHttpResponse<'null'>> {
    const obs = logout(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Log out and clear the session cookie.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `logout$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  logout(params?: Logout$Params, context?: HttpContext): Promise<'null'> {
    const resp = this.logout$Response(params, context);
    return resp.then((r: StrictHttpResponse<'null'>): 'null' => r.body);
  }

  /** Path part for operation `getCurrentUser()` */
  static readonly GetCurrentUserPath = '/auth/me';

  /**
   * Get the current authenticated user.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getCurrentUser()` instead.
   *
   * This method doesn't expect any request body.
   */
  getCurrentUser$Response(params?: GetCurrentUser$Params, context?: HttpContext): Promise<StrictHttpResponse<{
'id': string;
'email': string;
'createdAt': string;
}>> {
    const obs = getCurrentUser(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Get the current authenticated user.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getCurrentUser$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getCurrentUser(params?: GetCurrentUser$Params, context?: HttpContext): Promise<{
'id': string;
'email': string;
'createdAt': string;
}> {
    const resp = this.getCurrentUser$Response(params, context);
    return resp.then((r: StrictHttpResponse<{
'id': string;
'email': string;
'createdAt': string;
}>): {
'id': string;
'email': string;
'createdAt': string;
} => r.body);
  }

}
