/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { createChatThread } from '../fn/chat/create-chat-thread';
import { CreateChatThread$Params } from '../fn/chat/create-chat-thread';
import { listChatMessages } from '../fn/chat/list-chat-messages';
import { ListChatMessages$Params } from '../fn/chat/list-chat-messages';
import { listChatThreads } from '../fn/chat/list-chat-threads';
import { ListChatThreads$Params } from '../fn/chat/list-chat-threads';
import { renameChatThread } from '../fn/chat/rename-chat-thread';
import { RenameChatThread$Params } from '../fn/chat/rename-chat-thread';
import { sendChatMessage } from '../fn/chat/send-chat-message';
import { SendChatMessage$Params } from '../fn/chat/send-chat-message';

@Injectable({ providedIn: 'root' })
export class ChatService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `listChatThreads()` */
  static readonly ListChatThreadsPath = '/notebooks/{notebookId}/threads';

  /**
   * List every Chat Thread in a Notebook.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `listChatThreads()` instead.
   *
   * This method doesn't expect any request body.
   */
  listChatThreads$Response(params: ListChatThreads$Params, context?: HttpContext): Promise<StrictHttpResponse<Array<{
'id': string;
'notebookId': string;
'title': string;
'author': {
'id': string;
'email': string;
};
'createdAt': string;
}>>> {
    const obs = listChatThreads(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * List every Chat Thread in a Notebook.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `listChatThreads$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  listChatThreads(params: ListChatThreads$Params, context?: HttpContext): Promise<Array<{
'id': string;
'notebookId': string;
'title': string;
'author': {
'id': string;
'email': string;
};
'createdAt': string;
}>> {
    const resp = this.listChatThreads$Response(params, context);
    return resp.then((r: StrictHttpResponse<Array<{
'id': string;
'notebookId': string;
'title': string;
'author': {
'id': string;
'email': string;
};
'createdAt': string;
}>>): Array<{
'id': string;
'notebookId': string;
'title': string;
'author': {
'id': string;
'email': string;
};
'createdAt': string;
}> => r.body);
  }

  /** Path part for operation `createChatThread()` */
  static readonly CreateChatThreadPath = '/notebooks/{notebookId}/threads';

  /**
   * Start a Chat Thread in a Notebook.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createChatThread()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createChatThread$Response(params: CreateChatThread$Params, context?: HttpContext): Promise<StrictHttpResponse<{
'id': string;
'notebookId': string;
'title': string;
'author': {
'id': string;
'email': string;
};
'createdAt': string;
}>> {
    const obs = createChatThread(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Start a Chat Thread in a Notebook.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createChatThread$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createChatThread(params: CreateChatThread$Params, context?: HttpContext): Promise<{
'id': string;
'notebookId': string;
'title': string;
'author': {
'id': string;
'email': string;
};
'createdAt': string;
}> {
    const resp = this.createChatThread$Response(params, context);
    return resp.then((r: StrictHttpResponse<{
'id': string;
'notebookId': string;
'title': string;
'author': {
'id': string;
'email': string;
};
'createdAt': string;
}>): {
'id': string;
'notebookId': string;
'title': string;
'author': {
'id': string;
'email': string;
};
'createdAt': string;
} => r.body);
  }

  /** Path part for operation `renameChatThread()` */
  static readonly RenameChatThreadPath = '/notebooks/{notebookId}/threads/{threadId}';

  /**
   * Rename a Chat Thread.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `renameChatThread()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  renameChatThread$Response(params: RenameChatThread$Params, context?: HttpContext): Promise<StrictHttpResponse<{
'id': string;
'notebookId': string;
'title': string;
'author': {
'id': string;
'email': string;
};
'createdAt': string;
}>> {
    const obs = renameChatThread(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Rename a Chat Thread.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `renameChatThread$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  renameChatThread(params: RenameChatThread$Params, context?: HttpContext): Promise<{
'id': string;
'notebookId': string;
'title': string;
'author': {
'id': string;
'email': string;
};
'createdAt': string;
}> {
    const resp = this.renameChatThread$Response(params, context);
    return resp.then((r: StrictHttpResponse<{
'id': string;
'notebookId': string;
'title': string;
'author': {
'id': string;
'email': string;
};
'createdAt': string;
}>): {
'id': string;
'notebookId': string;
'title': string;
'author': {
'id': string;
'email': string;
};
'createdAt': string;
} => r.body);
  }

  /** Path part for operation `listChatMessages()` */
  static readonly ListChatMessagesPath = '/notebooks/{notebookId}/threads/{threadId}/messages';

  /**
   * Read a Chat Thread's conversation.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `listChatMessages()` instead.
   *
   * This method doesn't expect any request body.
   */
  listChatMessages$Response(params: ListChatMessages$Params, context?: HttpContext): Promise<StrictHttpResponse<Array<{
'id': string;
'threadId': string;
'role': 'user' | 'assistant';
'content': string;
'askedBy': {
'id': string;
'email': string;
};
'citations': Array<{
'id': string;
'marker': number;
'documentId': string;
'documentVersionId': string;
'versionNumber': number;
'chunkId': string;
'filename': string;
'headingPath': Array<string>;
'charStart': number | null;
'charEnd': number | null;
}>;
'createdAt': string;
}>>> {
    const obs = listChatMessages(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Read a Chat Thread's conversation.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `listChatMessages$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  listChatMessages(params: ListChatMessages$Params, context?: HttpContext): Promise<Array<{
'id': string;
'threadId': string;
'role': 'user' | 'assistant';
'content': string;
'askedBy': {
'id': string;
'email': string;
};
'citations': Array<{
'id': string;
'marker': number;
'documentId': string;
'documentVersionId': string;
'versionNumber': number;
'chunkId': string;
'filename': string;
'headingPath': Array<string>;
'charStart': number | null;
'charEnd': number | null;
}>;
'createdAt': string;
}>> {
    const resp = this.listChatMessages$Response(params, context);
    return resp.then((r: StrictHttpResponse<Array<{
'id': string;
'threadId': string;
'role': 'user' | 'assistant';
'content': string;
'askedBy': {
'id': string;
'email': string;
};
'citations': Array<{
'id': string;
'marker': number;
'documentId': string;
'documentVersionId': string;
'versionNumber': number;
'chunkId': string;
'filename': string;
'headingPath': Array<string>;
'charStart': number | null;
'charEnd': number | null;
}>;
'createdAt': string;
}>>): Array<{
'id': string;
'threadId': string;
'role': 'user' | 'assistant';
'content': string;
'askedBy': {
'id': string;
'email': string;
};
'citations': Array<{
'id': string;
'marker': number;
'documentId': string;
'documentVersionId': string;
'versionNumber': number;
'chunkId': string;
'filename': string;
'headingPath': Array<string>;
'charStart': number | null;
'charEnd': number | null;
}>;
'createdAt': string;
}> => r.body);
  }

  /** Path part for operation `sendChatMessage()` */
  static readonly SendChatMessagePath = '/notebooks/{notebookId}/threads/{threadId}/messages';

  /**
   * Ask a question in a Chat Thread and get one grounded answer.
   *
   * Retrieves the closest Chunks from the Notebook's latest-version, `ready` Documents and returns one complete answer. The answer is not streamed. The answer message carries a Citation per source marker in its text, each pinned to the exact Document Version and chunk it was grounded in and persisted with the message.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `sendChatMessage()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  sendChatMessage$Response(params: SendChatMessage$Params, context?: HttpContext): Promise<StrictHttpResponse<{
'question': {
'id': string;
'threadId': string;
'role': 'user' | 'assistant';
'content': string;
'askedBy': {
'id': string;
'email': string;
};
'citations': Array<{
'id': string;
'marker': number;
'documentId': string;
'documentVersionId': string;
'versionNumber': number;
'chunkId': string;
'filename': string;
'headingPath': Array<string>;
'charStart': number | null;
'charEnd': number | null;
}>;
'createdAt': string;
};
'answer': {
'id': string;
'threadId': string;
'role': 'user' | 'assistant';
'content': string;
'askedBy': {
'id': string;
'email': string;
};
'citations': Array<{
'id': string;
'marker': number;
'documentId': string;
'documentVersionId': string;
'versionNumber': number;
'chunkId': string;
'filename': string;
'headingPath': Array<string>;
'charStart': number | null;
'charEnd': number | null;
}>;
'createdAt': string;
};
}>> {
    const obs = sendChatMessage(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Ask a question in a Chat Thread and get one grounded answer.
   *
   * Retrieves the closest Chunks from the Notebook's latest-version, `ready` Documents and returns one complete answer. The answer is not streamed. The answer message carries a Citation per source marker in its text, each pinned to the exact Document Version and chunk it was grounded in and persisted with the message.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `sendChatMessage$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  sendChatMessage(params: SendChatMessage$Params, context?: HttpContext): Promise<{
'question': {
'id': string;
'threadId': string;
'role': 'user' | 'assistant';
'content': string;
'askedBy': {
'id': string;
'email': string;
};
'citations': Array<{
'id': string;
'marker': number;
'documentId': string;
'documentVersionId': string;
'versionNumber': number;
'chunkId': string;
'filename': string;
'headingPath': Array<string>;
'charStart': number | null;
'charEnd': number | null;
}>;
'createdAt': string;
};
'answer': {
'id': string;
'threadId': string;
'role': 'user' | 'assistant';
'content': string;
'askedBy': {
'id': string;
'email': string;
};
'citations': Array<{
'id': string;
'marker': number;
'documentId': string;
'documentVersionId': string;
'versionNumber': number;
'chunkId': string;
'filename': string;
'headingPath': Array<string>;
'charStart': number | null;
'charEnd': number | null;
}>;
'createdAt': string;
};
}> {
    const resp = this.sendChatMessage$Response(params, context);
    return resp.then((r: StrictHttpResponse<{
'question': {
'id': string;
'threadId': string;
'role': 'user' | 'assistant';
'content': string;
'askedBy': {
'id': string;
'email': string;
};
'citations': Array<{
'id': string;
'marker': number;
'documentId': string;
'documentVersionId': string;
'versionNumber': number;
'chunkId': string;
'filename': string;
'headingPath': Array<string>;
'charStart': number | null;
'charEnd': number | null;
}>;
'createdAt': string;
};
'answer': {
'id': string;
'threadId': string;
'role': 'user' | 'assistant';
'content': string;
'askedBy': {
'id': string;
'email': string;
};
'citations': Array<{
'id': string;
'marker': number;
'documentId': string;
'documentVersionId': string;
'versionNumber': number;
'chunkId': string;
'filename': string;
'headingPath': Array<string>;
'charStart': number | null;
'charEnd': number | null;
}>;
'createdAt': string;
};
}>): {
'question': {
'id': string;
'threadId': string;
'role': 'user' | 'assistant';
'content': string;
'askedBy': {
'id': string;
'email': string;
};
'citations': Array<{
'id': string;
'marker': number;
'documentId': string;
'documentVersionId': string;
'versionNumber': number;
'chunkId': string;
'filename': string;
'headingPath': Array<string>;
'charStart': number | null;
'charEnd': number | null;
}>;
'createdAt': string;
};
'answer': {
'id': string;
'threadId': string;
'role': 'user' | 'assistant';
'content': string;
'askedBy': {
'id': string;
'email': string;
};
'citations': Array<{
'id': string;
'marker': number;
'documentId': string;
'documentVersionId': string;
'versionNumber': number;
'chunkId': string;
'filename': string;
'headingPath': Array<string>;
'charStart': number | null;
'charEnd': number | null;
}>;
'createdAt': string;
};
} => r.body);
  }

}
