/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { deleteDocument } from '../fn/documents/delete-document';
import { DeleteDocument$Params } from '../fn/documents/delete-document';
import { downloadDocumentVersion } from '../fn/documents/download-document-version';
import { DownloadDocumentVersion$Params } from '../fn/documents/download-document-version';
import { listDocuments } from '../fn/documents/list-documents';
import { ListDocuments$Params } from '../fn/documents/list-documents';
import { restoreDocument } from '../fn/documents/restore-document';
import { RestoreDocument$Params } from '../fn/documents/restore-document';
import { uploadDocument } from '../fn/documents/upload-document';
import { UploadDocument$Params } from '../fn/documents/upload-document';

@Injectable({ providedIn: 'root' })
export class DocumentsService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `listDocuments()` */
  static readonly ListDocumentsPath = '/notebooks/{notebookId}/documents';

  /**
   * List all Documents in a Notebook.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `listDocuments()` instead.
   *
   * This method doesn't expect any request body.
   */
  listDocuments$Response(params: ListDocuments$Params, context?: HttpContext): Promise<StrictHttpResponse<Array<{
'id': string;
'notebookId': string;
'filename': string;
'status': 'uploaded';
'createdAt': string;
'latestVersion': {
'id': string;
'versionNumber': number;
'mimeType': string;
'sizeBytes': number;
'createdAt': string;
};
}>>> {
    const obs = listDocuments(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * List all Documents in a Notebook.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `listDocuments$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  listDocuments(params: ListDocuments$Params, context?: HttpContext): Promise<Array<{
'id': string;
'notebookId': string;
'filename': string;
'status': 'uploaded';
'createdAt': string;
'latestVersion': {
'id': string;
'versionNumber': number;
'mimeType': string;
'sizeBytes': number;
'createdAt': string;
};
}>> {
    const resp = this.listDocuments$Response(params, context);
    return resp.then((r: StrictHttpResponse<Array<{
'id': string;
'notebookId': string;
'filename': string;
'status': 'uploaded';
'createdAt': string;
'latestVersion': {
'id': string;
'versionNumber': number;
'mimeType': string;
'sizeBytes': number;
'createdAt': string;
};
}>>): Array<{
'id': string;
'notebookId': string;
'filename': string;
'status': 'uploaded';
'createdAt': string;
'latestVersion': {
'id': string;
'versionNumber': number;
'mimeType': string;
'sizeBytes': number;
'createdAt': string;
};
}> => r.body);
  }

  /** Path part for operation `uploadDocument()` */
  static readonly UploadDocumentPath = '/notebooks/{notebookId}/documents';

  /**
   * Upload a Document. Re-uploading an existing, undeleted filename within the same Notebook adds a new Version to that Document instead of creating a new one.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `uploadDocument()` instead.
   *
   * This method doesn't expect any request body.
   */
  uploadDocument$Response(params: UploadDocument$Params, context?: HttpContext): Promise<StrictHttpResponse<{
'id': string;
'notebookId': string;
'filename': string;
'status': 'uploaded';
'createdAt': string;
'latestVersion': {
'id': string;
'versionNumber': number;
'mimeType': string;
'sizeBytes': number;
'createdAt': string;
};
}>> {
    const obs = uploadDocument(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Upload a Document. Re-uploading an existing, undeleted filename within the same Notebook adds a new Version to that Document instead of creating a new one.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `uploadDocument$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  uploadDocument(params: UploadDocument$Params, context?: HttpContext): Promise<{
'id': string;
'notebookId': string;
'filename': string;
'status': 'uploaded';
'createdAt': string;
'latestVersion': {
'id': string;
'versionNumber': number;
'mimeType': string;
'sizeBytes': number;
'createdAt': string;
};
}> {
    const resp = this.uploadDocument$Response(params, context);
    return resp.then((r: StrictHttpResponse<{
'id': string;
'notebookId': string;
'filename': string;
'status': 'uploaded';
'createdAt': string;
'latestVersion': {
'id': string;
'versionNumber': number;
'mimeType': string;
'sizeBytes': number;
'createdAt': string;
};
}>): {
'id': string;
'notebookId': string;
'filename': string;
'status': 'uploaded';
'createdAt': string;
'latestVersion': {
'id': string;
'versionNumber': number;
'mimeType': string;
'sizeBytes': number;
'createdAt': string;
};
} => r.body);
  }

  /** Path part for operation `deleteDocument()` */
  static readonly DeleteDocumentPath = '/notebooks/{notebookId}/documents/{documentId}';

  /**
   * Soft-delete a Document.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deleteDocument()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteDocument$Response(params: DeleteDocument$Params, context?: HttpContext): Promise<StrictHttpResponse<'null'>> {
    const obs = deleteDocument(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Soft-delete a Document.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deleteDocument$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteDocument(params: DeleteDocument$Params, context?: HttpContext): Promise<'null'> {
    const resp = this.deleteDocument$Response(params, context);
    return resp.then((r: StrictHttpResponse<'null'>): 'null' => r.body);
  }

  /** Path part for operation `restoreDocument()` */
  static readonly RestoreDocumentPath = '/notebooks/{notebookId}/documents/{documentId}/restore';

  /**
   * Restore a soft-deleted Document.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `restoreDocument()` instead.
   *
   * This method doesn't expect any request body.
   */
  restoreDocument$Response(params: RestoreDocument$Params, context?: HttpContext): Promise<StrictHttpResponse<{
'id': string;
'notebookId': string;
'filename': string;
'status': 'uploaded';
'createdAt': string;
'latestVersion': {
'id': string;
'versionNumber': number;
'mimeType': string;
'sizeBytes': number;
'createdAt': string;
};
}>> {
    const obs = restoreDocument(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Restore a soft-deleted Document.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `restoreDocument$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  restoreDocument(params: RestoreDocument$Params, context?: HttpContext): Promise<{
'id': string;
'notebookId': string;
'filename': string;
'status': 'uploaded';
'createdAt': string;
'latestVersion': {
'id': string;
'versionNumber': number;
'mimeType': string;
'sizeBytes': number;
'createdAt': string;
};
}> {
    const resp = this.restoreDocument$Response(params, context);
    return resp.then((r: StrictHttpResponse<{
'id': string;
'notebookId': string;
'filename': string;
'status': 'uploaded';
'createdAt': string;
'latestVersion': {
'id': string;
'versionNumber': number;
'mimeType': string;
'sizeBytes': number;
'createdAt': string;
};
}>): {
'id': string;
'notebookId': string;
'filename': string;
'status': 'uploaded';
'createdAt': string;
'latestVersion': {
'id': string;
'versionNumber': number;
'mimeType': string;
'sizeBytes': number;
'createdAt': string;
};
} => r.body);
  }

  /** Path part for operation `downloadDocumentVersion()` */
  static readonly DownloadDocumentVersionPath = '/notebooks/{notebookId}/documents/{documentId}/versions/{versionId}/download';

  /**
   * Download the exact original bytes uploaded for a Document Version.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `downloadDocumentVersion()` instead.
   *
   * This method doesn't expect any request body.
   */
  downloadDocumentVersion$Response(params: DownloadDocumentVersion$Params, context?: HttpContext): Promise<StrictHttpResponse<any>> {
    const obs = downloadDocumentVersion(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Download the exact original bytes uploaded for a Document Version.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `downloadDocumentVersion$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  downloadDocumentVersion(params: DownloadDocumentVersion$Params, context?: HttpContext): Promise<any> {
    const resp = this.downloadDocumentVersion$Response(params, context);
    return resp.then((r: StrictHttpResponse<any>): any => r.body);
  }

}
