/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { streamEvents } from '../fn/events/stream-events';
import { StreamEvents$Params } from '../fn/events/stream-events';

@Injectable({ providedIn: 'root' })
export class EventsService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `streamEvents()` */
  static readonly StreamEventsPath = '/events';

  /**
   * Subscribe to live app events over server-sent events. Generic: every event type (ingestion progress, and later chat streaming) arrives on this one stream.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `streamEvents()` instead.
   *
   * This method doesn't expect any request body.
   */
  streamEvents$Response(params?: StreamEvents$Params, context?: HttpContext): Promise<StrictHttpResponse<any>> {
    const obs = streamEvents(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Subscribe to live app events over server-sent events. Generic: every event type (ingestion progress, and later chat streaming) arrives on this one stream.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `streamEvents$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  streamEvents(params?: StreamEvents$Params, context?: HttpContext): Promise<any> {
    const resp = this.streamEvents$Response(params, context);
    return resp.then((r: StrictHttpResponse<any>): any => r.body);
  }

}
