/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { listNotebooks } from '../fn/notebooks/list-notebooks';
import { ListNotebooks$Params } from '../fn/notebooks/list-notebooks';

@Injectable({ providedIn: 'root' })
export class NotebooksService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `listNotebooks()` */
  static readonly ListNotebooksPath = '/notebooks';

  /**
   * List all Notebooks.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `listNotebooks()` instead.
   *
   * This method doesn't expect any request body.
   */
  listNotebooks$Response(params?: ListNotebooks$Params, context?: HttpContext): Promise<StrictHttpResponse<Array<{
'id': string;
'title': string;
'createdAt': string;
}>>> {
    const obs = listNotebooks(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * List all Notebooks.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `listNotebooks$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  listNotebooks(params?: ListNotebooks$Params, context?: HttpContext): Promise<Array<{
'id': string;
'title': string;
'createdAt': string;
}>> {
    const resp = this.listNotebooks$Response(params, context);
    return resp.then((r: StrictHttpResponse<Array<{
'id': string;
'title': string;
'createdAt': string;
}>>): Array<{
'id': string;
'title': string;
'createdAt': string;
}> => r.body);
  }

}
