/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { DocumentFailure } from '../models/document-failure';
import { searchNotebook } from '../fn/search/search-notebook';
import { SearchNotebook$Params } from '../fn/search/search-notebook';

@Injectable({ providedIn: 'root' })
export class SearchService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `searchNotebook()` */
  static readonly SearchNotebookPath = '/notebooks/{notebookId}/search';

  /**
   * Search a Notebook's Documents semantically. Matches Chunks by vector similarity, rolls them up to their parent Document, and returns each matched Document with its Abstract.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `searchNotebook()` instead.
   *
   * This method doesn't expect any request body.
   */
  searchNotebook$Response(params: SearchNotebook$Params, context?: HttpContext): Promise<StrictHttpResponse<Array<{
'id': string;
'notebookId': string;
'filename': string;
'status': 'queued' | 'converting' | 'converted' | 'summarizing' | 'summarized' | 'indexing' | 'ready' | 'failed';
'failure': DocumentFailure | null;
'abstract': string | null;
'createdAt': string;
'latestVersion': {
'id': string;
'versionNumber': number;
'mimeType': string;
'sizeBytes': number;
'createdAt': string;
};

/**
 * The title Stage 2 extracted from the Document's latest Version, or null when it stated none — what a result is headed by (NBK-96).
 */
'title': string | null;

/**
 * Where the Document's best-matching Chunk sits — what opening the result shows.
 */
'match': {

/**
 * The Document Version the Chunk belongs to.
 */
'versionId': string;

/**
 * The Document's best-matching Chunk.
 */
'chunkId': string;

/**
 * Start of the Chunk in the Version's Converted Markdown; null when it could not be located.
 */
'charStart': number | null;

/**
 * End of that range, exclusive.
 */
'charEnd': number | null;
};

/**
 * Cosine similarity of this Document's best-matching Chunk to the query, 1 being identical. Results are ordered by it, best first.
 */
'score': number;
}>>> {
    const obs = searchNotebook(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Search a Notebook's Documents semantically. Matches Chunks by vector similarity, rolls them up to their parent Document, and returns each matched Document with its Abstract.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `searchNotebook$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  searchNotebook(params: SearchNotebook$Params, context?: HttpContext): Promise<Array<{
'id': string;
'notebookId': string;
'filename': string;
'status': 'queued' | 'converting' | 'converted' | 'summarizing' | 'summarized' | 'indexing' | 'ready' | 'failed';
'failure': DocumentFailure | null;
'abstract': string | null;
'createdAt': string;
'latestVersion': {
'id': string;
'versionNumber': number;
'mimeType': string;
'sizeBytes': number;
'createdAt': string;
};

/**
 * The title Stage 2 extracted from the Document's latest Version, or null when it stated none — what a result is headed by (NBK-96).
 */
'title': string | null;

/**
 * Where the Document's best-matching Chunk sits — what opening the result shows.
 */
'match': {

/**
 * The Document Version the Chunk belongs to.
 */
'versionId': string;

/**
 * The Document's best-matching Chunk.
 */
'chunkId': string;

/**
 * Start of the Chunk in the Version's Converted Markdown; null when it could not be located.
 */
'charStart': number | null;

/**
 * End of that range, exclusive.
 */
'charEnd': number | null;
};

/**
 * Cosine similarity of this Document's best-matching Chunk to the query, 1 being identical. Results are ordered by it, best first.
 */
'score': number;
}>> {
    const resp = this.searchNotebook$Response(params, context);
    return resp.then((r: StrictHttpResponse<Array<{
'id': string;
'notebookId': string;
'filename': string;
'status': 'queued' | 'converting' | 'converted' | 'summarizing' | 'summarized' | 'indexing' | 'ready' | 'failed';
'failure': DocumentFailure | null;
'abstract': string | null;
'createdAt': string;
'latestVersion': {
'id': string;
'versionNumber': number;
'mimeType': string;
'sizeBytes': number;
'createdAt': string;
};

/**
 * The title Stage 2 extracted from the Document's latest Version, or null when it stated none — what a result is headed by (NBK-96).
 */
'title': string | null;

/**
 * Where the Document's best-matching Chunk sits — what opening the result shows.
 */
'match': {

/**
 * The Document Version the Chunk belongs to.
 */
'versionId': string;

/**
 * The Document's best-matching Chunk.
 */
'chunkId': string;

/**
 * Start of the Chunk in the Version's Converted Markdown; null when it could not be located.
 */
'charStart': number | null;

/**
 * End of that range, exclusive.
 */
'charEnd': number | null;
};

/**
 * Cosine similarity of this Document's best-matching Chunk to the query, 1 being identical. Results are ordered by it, best first.
 */
'score': number;
}>>): Array<{
'id': string;
'notebookId': string;
'filename': string;
'status': 'queued' | 'converting' | 'converted' | 'summarizing' | 'summarized' | 'indexing' | 'ready' | 'failed';
'failure': DocumentFailure | null;
'abstract': string | null;
'createdAt': string;
'latestVersion': {
'id': string;
'versionNumber': number;
'mimeType': string;
'sizeBytes': number;
'createdAt': string;
};

/**
 * The title Stage 2 extracted from the Document's latest Version, or null when it stated none — what a result is headed by (NBK-96).
 */
'title': string | null;

/**
 * Where the Document's best-matching Chunk sits — what opening the result shows.
 */
'match': {

/**
 * The Document Version the Chunk belongs to.
 */
'versionId': string;

/**
 * The Document's best-matching Chunk.
 */
'chunkId': string;

/**
 * Start of the Chunk in the Version's Converted Markdown; null when it could not be located.
 */
'charStart': number | null;

/**
 * End of that range, exclusive.
 */
'charEnd': number | null;
};

/**
 * Cosine similarity of this Document's best-matching Chunk to the query, 1 being identical. Results are ordered by it, best first.
 */
'score': number;
}> => r.body);
  }

}
