/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { searchChatThreads } from '../fn/search/search-chat-threads';
import { SearchChatThreads$Params } from '../fn/search/search-chat-threads';
import { searchNotebook } from '../fn/search/search-notebook';
import { SearchNotebook$Params } from '../fn/search/search-notebook';

@Injectable({ providedIn: 'root' })
export class SearchService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `searchNotebook()` */
  static readonly SearchNotebookPath = '/notebooks/{notebookId}/search';

  /**
   * Search a Notebook's Documents by keyword. Returns each matching Chunk as an Excerpt with its matches marked; up to 20, best first.
   *
   * Full-text search over the Chunks of each Document's latest ready Version, accents and case ignored (no embedding, so it needs no OpenRouter key). A Document appears once per matching Chunk. Per ADR-0001 there is no ownership check.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `searchNotebook()` instead.
   *
   * This method doesn't expect any request body.
   */
  searchNotebook$Response(params: SearchNotebook$Params, context?: HttpContext): Promise<StrictHttpResponse<Array<{
'documentId': string;
'filename': string;

/**
 * The title Stage 2 extracted from the Version, or null when it stated none.
 */
'title': string | null;

/**
 * The Markdown headings the Chunk sits under, outermost first.
 */
'headingPath': Array<string>;

/**
 * Where the matching Chunk sits — what opening the result shows.
 */
'match': {

/**
 * The Document Version the Chunk belongs to.
 */
'versionId': string;

/**
 * The matching Chunk.
 */
'chunkId': string;

/**
 * Start of the Chunk in the Version's Converted Markdown; null when it could not be located.
 */
'charStart': number | null;

/**
 * End of that range, exclusive.
 */
'charEnd': number | null;
};

/**
 * An Excerpt (GLOSSARY.md): about two lines of the Chunk around its matches, Markdown markers stripped, the matched words flagged.
 */
'excerpt': Array<{
'text': string;
'match': boolean;
}>;
}>>> {
    const obs = searchNotebook(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Search a Notebook's Documents by keyword. Returns each matching Chunk as an Excerpt with its matches marked; up to 20, best first.
   *
   * Full-text search over the Chunks of each Document's latest ready Version, accents and case ignored (no embedding, so it needs no OpenRouter key). A Document appears once per matching Chunk. Per ADR-0001 there is no ownership check.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `searchNotebook$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  searchNotebook(params: SearchNotebook$Params, context?: HttpContext): Promise<Array<{
'documentId': string;
'filename': string;

/**
 * The title Stage 2 extracted from the Version, or null when it stated none.
 */
'title': string | null;

/**
 * The Markdown headings the Chunk sits under, outermost first.
 */
'headingPath': Array<string>;

/**
 * Where the matching Chunk sits — what opening the result shows.
 */
'match': {

/**
 * The Document Version the Chunk belongs to.
 */
'versionId': string;

/**
 * The matching Chunk.
 */
'chunkId': string;

/**
 * Start of the Chunk in the Version's Converted Markdown; null when it could not be located.
 */
'charStart': number | null;

/**
 * End of that range, exclusive.
 */
'charEnd': number | null;
};

/**
 * An Excerpt (GLOSSARY.md): about two lines of the Chunk around its matches, Markdown markers stripped, the matched words flagged.
 */
'excerpt': Array<{
'text': string;
'match': boolean;
}>;
}>> {
    const resp = this.searchNotebook$Response(params, context);
    return resp.then((r: StrictHttpResponse<Array<{
'documentId': string;
'filename': string;

/**
 * The title Stage 2 extracted from the Version, or null when it stated none.
 */
'title': string | null;

/**
 * The Markdown headings the Chunk sits under, outermost first.
 */
'headingPath': Array<string>;

/**
 * Where the matching Chunk sits — what opening the result shows.
 */
'match': {

/**
 * The Document Version the Chunk belongs to.
 */
'versionId': string;

/**
 * The matching Chunk.
 */
'chunkId': string;

/**
 * Start of the Chunk in the Version's Converted Markdown; null when it could not be located.
 */
'charStart': number | null;

/**
 * End of that range, exclusive.
 */
'charEnd': number | null;
};

/**
 * An Excerpt (GLOSSARY.md): about two lines of the Chunk around its matches, Markdown markers stripped, the matched words flagged.
 */
'excerpt': Array<{
'text': string;
'match': boolean;
}>;
}>>): Array<{
'documentId': string;
'filename': string;

/**
 * The title Stage 2 extracted from the Version, or null when it stated none.
 */
'title': string | null;

/**
 * The Markdown headings the Chunk sits under, outermost first.
 */
'headingPath': Array<string>;

/**
 * Where the matching Chunk sits — what opening the result shows.
 */
'match': {

/**
 * The Document Version the Chunk belongs to.
 */
'versionId': string;

/**
 * The matching Chunk.
 */
'chunkId': string;

/**
 * Start of the Chunk in the Version's Converted Markdown; null when it could not be located.
 */
'charStart': number | null;

/**
 * End of that range, exclusive.
 */
'charEnd': number | null;
};

/**
 * An Excerpt (GLOSSARY.md): about two lines of the Chunk around its matches, Markdown markers stripped, the matched words flagged.
 */
'excerpt': Array<{
'text': string;
'match': boolean;
}>;
}> => r.body);
  }

  /** Path part for operation `searchChatThreads()` */
  static readonly SearchChatThreadsPath = '/notebooks/{notebookId}/search/threads';

  /**
   * Search a Notebook's Chat Threads by keyword. Returns each matching Exchange — a question and the answer it produced — with its matches marked; up to 20, best first.
   *
   * Full-text search over questions and answers, accents and case ignored (no embedding, so it needs no OpenRouter key). Deleted Chat Threads are left out. Per ADR-0001 there is no ownership check.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `searchChatThreads()` instead.
   *
   * This method doesn't expect any request body.
   */
  searchChatThreads$Response(params: SearchChatThreads$Params, context?: HttpContext): Promise<StrictHttpResponse<Array<{
'threadId': string;
'threadTitle': string;
'askedBy': {
'id': string;
'email': string;
};

/**
 * When the question was asked.
 */
'askedAt': string;
'questionId': string;

/**
 * Where a result opens the Chat Thread.
 */
'answerId': string;

/**
 * The question, whole, its matches flagged.
 */
'question': Array<{
'text': string;
'match': boolean;
}>;

/**
 * Up to two excerpts of the answer around its matches, flagged.
 */
'answer': Array<{
'text': string;
'match': boolean;
}>;
}>>> {
    const obs = searchChatThreads(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Search a Notebook's Chat Threads by keyword. Returns each matching Exchange — a question and the answer it produced — with its matches marked; up to 20, best first.
   *
   * Full-text search over questions and answers, accents and case ignored (no embedding, so it needs no OpenRouter key). Deleted Chat Threads are left out. Per ADR-0001 there is no ownership check.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `searchChatThreads$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  searchChatThreads(params: SearchChatThreads$Params, context?: HttpContext): Promise<Array<{
'threadId': string;
'threadTitle': string;
'askedBy': {
'id': string;
'email': string;
};

/**
 * When the question was asked.
 */
'askedAt': string;
'questionId': string;

/**
 * Where a result opens the Chat Thread.
 */
'answerId': string;

/**
 * The question, whole, its matches flagged.
 */
'question': Array<{
'text': string;
'match': boolean;
}>;

/**
 * Up to two excerpts of the answer around its matches, flagged.
 */
'answer': Array<{
'text': string;
'match': boolean;
}>;
}>> {
    const resp = this.searchChatThreads$Response(params, context);
    return resp.then((r: StrictHttpResponse<Array<{
'threadId': string;
'threadTitle': string;
'askedBy': {
'id': string;
'email': string;
};

/**
 * When the question was asked.
 */
'askedAt': string;
'questionId': string;

/**
 * Where a result opens the Chat Thread.
 */
'answerId': string;

/**
 * The question, whole, its matches flagged.
 */
'question': Array<{
'text': string;
'match': boolean;
}>;

/**
 * Up to two excerpts of the answer around its matches, flagged.
 */
'answer': Array<{
'text': string;
'match': boolean;
}>;
}>>): Array<{
'threadId': string;
'threadTitle': string;
'askedBy': {
'id': string;
'email': string;
};

/**
 * When the question was asked.
 */
'askedAt': string;
'questionId': string;

/**
 * Where a result opens the Chat Thread.
 */
'answerId': string;

/**
 * The question, whole, its matches flagged.
 */
'question': Array<{
'text': string;
'match': boolean;
}>;

/**
 * Up to two excerpts of the answer around its matches, flagged.
 */
'answer': Array<{
'text': string;
'match': boolean;
}>;
}> => r.body);
  }

}
