/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface DownloadDocumentVersion$Params {
  notebookId: string;
  documentId: string;
  versionId: string;
}

export function downloadDocumentVersion(http: HttpClient, rootUrl: string, params: DownloadDocumentVersion$Params, context?: HttpContext): Observable<StrictHttpResponse<any>> {
  const rb = new RequestBuilder(rootUrl, downloadDocumentVersion.PATH, 'get');
  if (params) {
    rb.path('notebookId', params.notebookId, {});
    rb.path('documentId', params.documentId, {});
    rb.path('versionId', params.versionId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<any>;
    })
  );
}

downloadDocumentVersion.PATH = '/notebooks/{notebookId}/documents/{documentId}/versions/{versionId}/download';
