/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface GetDocumentVersion$Params {
  notebookId: string;
  documentId: string;
  versionId: string;
}

export function getDocumentVersion(http: HttpClient, rootUrl: string, params: GetDocumentVersion$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'documentId': string;
'notebookId': string;
'filename': string;
'documentCreatedAt': string;
'version': {
'id': string;
'versionNumber': number;
'mimeType': string;
'sizeBytes': number;
'createdAt': string;
};
'status': 'queued' | 'converting' | 'converted' | 'summarizing' | 'summarized' | 'indexing' | 'ready' | 'failed';
'abstract': string | null;
'chatSnippet': string | null;
'executiveSummary': string | null;
'metadata': ({
[key: string]: any;
}) | null;
'isLatestVersion': boolean;
'latestVersionNumber': number;
}>> {
  const rb = new RequestBuilder(rootUrl, getDocumentVersion.PATH, 'get');
  if (params) {
    rb.path('notebookId', params.notebookId, {});
    rb.path('documentId', params.documentId, {});
    rb.path('versionId', params.versionId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      'documentId': string;
      'notebookId': string;
      'filename': string;
      'documentCreatedAt': string;
      'version': {
      'id': string;
      'versionNumber': number;
      'mimeType': string;
      'sizeBytes': number;
      'createdAt': string;
      };
      'status': 'queued' | 'converting' | 'converted' | 'summarizing' | 'summarized' | 'indexing' | 'ready' | 'failed';
      'abstract': string | null;
      'chatSnippet': string | null;
      'executiveSummary': string | null;
      'metadata': ({
      [key: string]: any;
      }) | null;
      'isLatestVersion': boolean;
      'latestVersionNumber': number;
      }>;
    })
  );
}

getDocumentVersion.PATH = '/notebooks/{notebookId}/documents/{documentId}/versions/{versionId}';
