/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DocumentFailure } from '../../models/document-failure';

export interface ListDocuments$Params {
  notebookId: string;
}

export function listDocuments(http: HttpClient, rootUrl: string, params: ListDocuments$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<{
'id': string;
'notebookId': string;
'filename': string;
'status': 'queued' | 'converting' | 'converted' | 'summarizing' | 'summarized' | 'indexing' | 'ready' | 'failed';
'failure': DocumentFailure | null;
'abstract': string | null;
'createdAt': string;
'latestVersion': {
'id': string;
'versionNumber': number;
'mimeType': string;
'sizeBytes': number;
'createdAt': string;
};
}>>> {
  const rb = new RequestBuilder(rootUrl, listDocuments.PATH, 'get');
  if (params) {
    rb.path('notebookId', params.notebookId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<{
      'id': string;
      'notebookId': string;
      'filename': string;
      'status': 'queued' | 'converting' | 'converted' | 'summarizing' | 'summarized' | 'indexing' | 'ready' | 'failed';
      'failure': DocumentFailure | null;
      'abstract': string | null;
      'createdAt': string;
      'latestVersion': {
      'id': string;
      'versionNumber': number;
      'mimeType': string;
      'sizeBytes': number;
      'createdAt': string;
      };
      }>>;
    })
  );
}

listDocuments.PATH = '/notebooks/{notebookId}/documents';
