/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface RetryIngestion$Params {
  notebookId: string;
  documentId: string;
  versionId: string;
}

export function retryIngestion(http: HttpClient, rootUrl: string, params: RetryIngestion$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'status': 'queued' | 'converting' | 'converted' | 'summarizing' | 'summarized' | 'indexing' | 'ready' | 'failed';
}>> {
  const rb = new RequestBuilder(rootUrl, retryIngestion.PATH, 'post');
  if (params) {
    rb.path('notebookId', params.notebookId, {});
    rb.path('documentId', params.documentId, {});
    rb.path('versionId', params.versionId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      'status': 'queued' | 'converting' | 'converted' | 'summarizing' | 'summarized' | 'indexing' | 'ready' | 'failed';
      }>;
    })
  );
}

retryIngestion.PATH = '/notebooks/{notebookId}/documents/{documentId}/versions/{versionId}/retry';
