/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface UploadDocument$Params {
  notebookId: string;
}

export function uploadDocument(http: HttpClient, rootUrl: string, params: UploadDocument$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'id': string;
'notebookId': string;
'filename': string;
'status': 'queued' | 'converting' | 'converted' | 'summarizing' | 'summarized' | 'failed';
'abstract': string | null;
'createdAt': string;
'latestVersion': {
'id': string;
'versionNumber': number;
'mimeType': string;
'sizeBytes': number;
'createdAt': string;
};
}>> {
  const rb = new RequestBuilder(rootUrl, uploadDocument.PATH, 'post');
  if (params) {
    rb.path('notebookId', params.notebookId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      'id': string;
      'notebookId': string;
      'filename': string;
      'status': 'queued' | 'converting' | 'converted' | 'summarizing' | 'summarized' | 'failed';
      'abstract': string | null;
      'createdAt': string;
      'latestVersion': {
      'id': string;
      'versionNumber': number;
      'mimeType': string;
      'sizeBytes': number;
      'createdAt': string;
      };
      }>;
    })
  );
}

uploadDocument.PATH = '/notebooks/{notebookId}/documents';
