/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface DocumentFailure {
  failedAt: ('converting' | 'summarizing' | 'indexing') | null;
  reason: 'no-text-layer' | 'unreadable' | 'timed-out' | 'service-unavailable' | 'unexpected';
}
