import { Injectable, inject } from '@angular/core';
import { Observable, finalize, share } from 'rxjs';
import { ApiConfiguration } from '../api/api-configuration';

/**
 * One thing that happened on the backend, as it arrives over SSE. Mirrors
 * `apps/backend/src/events/schema.ts`.
 *
 * Deliberately generic (NBK-6): ingestion status changes are the first event
 * type, but chat answer chunks and other background-task progress arrive on
 * this same stream. `data` is therefore untyped here — each consumer narrows
 * the event types it cares about.
 */
export interface AppEvent {
  id: string;
  type: string;
  topic: string;
  occurredAt: string;
  data: Record<string, unknown>;
}

/**
 * The browser's half of the live-update plumbing: one SSE connection to
 * `GET /events`, carrying every event type.
 *
 * This is not generated by ng-openapi-gen, and can't be: the generated client
 * is built on `HttpClient`, which buffers a response and has no notion of a
 * body that never ends. The same documented escape hatch as
 * `DocumentTransferService` (see its file), for the same reason.
 *
 * `EventSource` rather than a hand-rolled fetch-and-parse loop because the
 * browser already implements SSE framing and automatic reconnection. Note
 * that an `EventSource` reconnect replays nothing — the backend's
 * LISTEN/NOTIFY bus has no history — so a consumer must treat events as
 * hints and keep the REST routes as its source of truth.
 */
@Injectable({ providedIn: 'root' })
export class AppEventsService {
  private readonly config = inject(ApiConfiguration);

  /**
   * The live connections, by topic set.
   *
   * One connection per topic set, however many consumers there are: a
   * Notebook page has several (Document statuses, and since NBK-11 chat
   * answers), and ADR-0004's design is "one NOTIFY channel, one `GET /events`
   * endpoint" — a connection per store would multiply exactly the thing that
   * was made generic to stay single, against a browser limit of about six
   * per origin. An entry is removed when its last subscriber leaves, so a
   * later watcher opens a fresh connection rather than reviving a closed one.
   */
  private readonly connections = new Map<string, Observable<AppEvent>>();

  /**
   * Opens a stream of the given topics (e.g. `notebook:<uuid>`), or of
   * everything if `topics` is empty. The connection is opened when the first
   * subscriber arrives and closed when the last one leaves, so a component
   * that stops watching stops costing a connection.
   */
  stream(topics: string[] = []): Observable<AppEvent> {
    const query = topics.map((topic) => `topic=${encodeURIComponent(topic)}`).join('&');
    const existing = this.connections.get(query);
    if (existing) return existing;

    const connection = new Observable<AppEvent>((subscriber) => {
      const url = `${this.config.rootUrl}/events${query ? `?${query}` : ''}`;
      // The session cookie is httpOnly and the backend is a different origin
      // in development, so the connection must be told to send credentials —
      // the same reason `withCredentialsInterceptor` exists for HttpClient.
      const source = new EventSource(url, { withCredentials: true });

      const forward = (event: MessageEvent<string>): void => {
        try {
          subscriber.next(JSON.parse(event.data) as AppEvent);
        } catch {
          // A frame we can't parse is not worth tearing the stream down for.
        }
      };

      // The backend sends unnamed SSE frames on purpose (see
      // apps/backend/src/events/routes.ts), so this single `message` listener
      // receives every event type. Each consumer switches on `event.type`.
      source.addEventListener('message', forward as EventListener);
      // An SSE error is usually the browser about to reconnect on its own, so
      // it must not complete or error the observable — that would drop the
      // consumer's subscription for what is a recoverable blip.
      source.addEventListener('error', () => undefined);

      return () => {
        source.removeEventListener('message', forward as EventListener);
        source.close();
      };
    }).pipe(
      // Before `share`, so it runs when the *connection* is torn down (the
      // last subscriber leaving) rather than per subscriber.
      finalize(() => this.connections.delete(query)),
      // Multicast: every consumer of this topic set reads one connection.
      // Plain `share`, not `shareReplay`: App Events are notifications about
      // something that already happened, so replaying an old one to a late
      // subscriber would tell it about a change it has already read over the
      // REST routes (GLOSSARY.md, App Event).
      share(),
    );

    this.connections.set(query, connection);
    return connection;
  }
}
