import { Injectable, inject } from '@angular/core';
import { Observable } from 'rxjs';
import { ApiConfiguration } from '../api/api-configuration';

/**
 * One thing that happened on the backend, as it arrives over SSE. Mirrors
 * `apps/backend/src/events/schema.ts`.
 *
 * Deliberately generic (NBK-6): ingestion status changes are the first event
 * type, but chat answer chunks and other background-task progress arrive on
 * this same stream. `data` is therefore untyped here — each consumer narrows
 * the event types it cares about.
 */
export interface AppEvent {
  id: string;
  type: string;
  topic: string;
  occurredAt: string;
  data: Record<string, unknown>;
}

/**
 * The browser's half of the live-update plumbing: one SSE connection to
 * `GET /events`, carrying every event type.
 *
 * This is not generated by ng-openapi-gen, and can't be: the generated client
 * is built on `HttpClient`, which buffers a response and has no notion of a
 * body that never ends. The same documented escape hatch as
 * `DocumentTransferService` (see its file), for the same reason.
 *
 * `EventSource` rather than a hand-rolled fetch-and-parse loop because the
 * browser already implements SSE framing and automatic reconnection. Note
 * that an `EventSource` reconnect replays nothing — the backend's
 * LISTEN/NOTIFY bus has no history — so a consumer must treat events as
 * hints and keep the REST routes as its source of truth.
 */
@Injectable({ providedIn: 'root' })
export class AppEventsService {
  private readonly config = inject(ApiConfiguration);

  /**
   * Opens a stream of the given topics (e.g. `notebook:<uuid>`), or of
   * everything if `topics` is empty. The connection is opened when the
   * returned observable is subscribed to and closed when the last subscriber
   * unsubscribes, so a component that stops watching stops costing a
   * connection.
   */
  stream(topics: string[] = []): Observable<AppEvent> {
    return new Observable<AppEvent>((subscriber) => {
      const query = topics.map((topic) => `topic=${encodeURIComponent(topic)}`).join('&');
      const url = `${this.config.rootUrl}/events${query ? `?${query}` : ''}`;
      // The session cookie is httpOnly and the backend is a different origin
      // in development, so the connection must be told to send credentials —
      // the same reason `withCredentialsInterceptor` exists for HttpClient.
      const source = new EventSource(url, { withCredentials: true });

      const forward = (event: MessageEvent<string>): void => {
        try {
          subscriber.next(JSON.parse(event.data) as AppEvent);
        } catch {
          // A frame we can't parse is not worth tearing the stream down for.
        }
      };

      // The backend sends unnamed SSE frames on purpose (see
      // apps/backend/src/events/routes.ts), so this single `message` listener
      // receives every event type. Each consumer switches on `event.type`.
      source.addEventListener('message', forward as EventListener);
      // An SSE error is usually the browser about to reconnect on its own, so
      // it must not complete or error the observable — that would drop the
      // consumer's subscription for what is a recoverable blip.
      source.addEventListener('error', () => undefined);

      return () => {
        source.removeEventListener('message', forward as EventListener);
        source.close();
      };
    });
  }
}
